- hosts: localhost
  become: true

  tasks:
  - name: Install fcitx5, fcitx5-mozc, fonts-firacode, htop, neovim, peek, wireguard, zsh
    apt:
      name: 
        - fcitx5
        - fcitx5-mozc
        - fonts-firacode
        - htop
        - neovim
        - peek
        - wireguard
        - zsh
      install_recommends: yes
      state: latest
      update_cache: yes
    tags: essentials

  - name: Change shell to zsh
    shell: chsh -s `which zsh`
    tags: essentials

  # TODO: Rename file only if it exists
  - name: Rename /etc/profile.d/pop-im-ibus.sh
    shell: /bin/mv /etc/profile.d/pop-im-ibus.sh /etc/profile.d/pop-im-ibus.sh.bak
    ignore_errors: yes
    tags: essentials

  - name: Switch to fcitx5
    command: im-config -n fcitx5
    tags: essentials

  - include: tasks/azure-cli.yml
    tags: azure-cli
  - include: tasks/chrome-vscode.yml
    tags: chrome-vscode
  - include: tasks/docker.yml
    tags: docker
  - include: tasks/gcloud-cli-kubectl.yml
    tags: gcloud-cli-kubectl
  - include: tasks/gh.yml
    tags: gh
  - include: tasks/go.yml
    tags: go
  - include: tasks/ngrok.yml
    tags: ngrok
  - include: tasks/oh-my-zsh.yml
    tags: oh-my-zsh
  - include: tasks/screenrec.yml
    tags: screenrec
  - include: tasks/slack.yml
    tags: slack
  - include: tasks/tailscale.yml
    tags: tailscale
  - include: tasks/terraform.yml
    tags: terraform
  - include: tasks/volta-node.yml
    tags: volta-node
