
- name: Install Google Chrome
  apt: 
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Install Visual Studio Code
  apt: 
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
