- name: Install GPG key
  get_url:
    url:  https://packagecloud.io/slacktechnologies/slack/gpgkey
    dest: /etc/apt/keyrings/slack.asc
    mode: '0644'
    force: true

- name: Install PPA
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/slack.asc] https://packagecloud.io/slacktechnologies/slack/debian/ jessie main"
    state: present

- name: Install apt package
  apt:
    name: slack-desktop
    state: latest
